server:
    port: 8000

spring:
  datasource:
    password: Surya@555
    url: jdbc:mysql://localhost:3306/movies?createDatabaseIfNotExist=true
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: admin
      # password: admin123  # Uncomment if you need to use this

  mail:
    host: smtp.gmail.com         # Use Gmail's SMTP server
    port: 587                    # Port for TLS (587 for TLS, 465 for SSL)
    username: suryatejayatam9866@gmail.com  # Your Gmail email address
    password: lgaajgfnzzylrulr  # Your Gmail password or app-specific password
    properties:
      mail:
        smtp:
          auth: true               # Enable SMTP authentication
          starttls:
            enable: true           # Enable STARTTLS for secure communication
    default-encoding: UTF-8        # Default character encoding
    protocol: smtp                 # Email protocol (smtp or smtps)
    test-connection: true

# Enable debug logging
logging:
  level:
    root: DEBUG
